[project]
name = "file-organizer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ijson>=3.4.0",
    "loguru>=0.7.3",
    "pyyml>=0.0.2",
    "rich>=14.1.0",
    "tqdm>=4.67.1",
    "typer>=0.16.0",
]
