"Documents":
  "extensions": [
    ".txt",
    ".pdf",
    ".docx",
    ".doc",
    ".xlsx",
    ".xls",
    ".pptx",
    ".ppt",
    ".odt",
    ".ods",
    ".csv",
    ".db",
    ".mdb",
  ]
"Images-Small":
  "extensions": &images_extensions [
    ".jpg",
    ".jpeg",
    ".png",
    ".gif",
    ".svg",
    ".webp",
    ".bmp",
    ".tiff",
    ".ico",
  ]
  "size_gt_mb": !!int 0
"Images-Medium":
  "extensions": *images_extensions
  "size_gt_mb": !!int 1
"Images-Large":
  "extensions": *images_extensions
  "size_gt_mb": !!int 5
"Images-Extra-Large":
  "extensions": *images_extensions
  "size_gt_mb": !!int 10
"Videos":
  "extensions": [
    ".mp4",
    ".avi",
    ".mkv",
    ".mov",
    ".wmv",
    ".flv",
    ".webm",
    ".mpeg",
    ".mpg",
  ]
"Audio":
  "extensions": [
    ".mp3",
    ".wav",
    ".aac",
    ".ogg",
    ".flac",
    ".m4a",
    ".wma",
  ]
"Archives":
  "extensions": [
    ".zip",
    ".rar",
    ".tar",
    ".gz",
    ".7z",
  ]
"Executable":
  "extensions": [
    ".exe",
    ".msi",
    ".bat",
    ".sh",
    ".cmd",
  ]
"Scripts":
  "extensions": [
    ".py",
    ".js",
    ".ts",
    ".java",
    ".c",
    ".cpp",
    ".cs",
    ".rb",
    ".php",
    ".go",
    ".html",
    ".css",
    ".xml",
  ]
"Configuration":
  "extensions": [
    ".yaml",
    ".yml",
    ".json",
    ".ini",
    ".conf",
    ".toml",
  ]
"Fonts":
  "extensions": [
    ".ttf",
    ".otf",
    ".woff",
    ".woff2",
  ]
"Miscellaneous":
  "extensions": [
    ".log",
    ".tmp",
    ".bak",
    ".md",
    ".rtf",
    ".epub",
    ".mobi",
    ".azw3",
    ".torrent",
    ".iso",
    ".dmg",
    ".apk",
    ".ipa",
    ".bin",
    ".cue",
    ".nfo",
    ".torrent",
    ".part",
    ".torrent",
    ".torrent",
  ]
"Database":
  "extensions": [
    ".sqlite",
    ".db3",
    ".dbf",
    ".mdb",
    ".accdb",
  ] 
"Date":
  "extensions": [
    ".ics",
    ".ical",
    ".vcs",
  ]
"3D Models":
  "extensions": [
    ".stl",
    ".obj",
    ".fbx",
    ".gltf",
    ".glb",
  ]